name: 'Add Issue Card'
description: 'Adding Issue Card'
author: 'PDIAMOND'
inputs:
  myInput:
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'addIssueCard.js'
