name: "Creating PR Review Checklist"
on:
 pull_request:
    types: [opened]
jobs:
  testing_action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm install
      run: cd ./actions && npm install
    - uses: ./pullRequests
      with: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
