name: 'Testing Multiple Actions'
on: [pull_request, issues]
jobs:
  testing_action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm install
      run: npm install
    - uses: action.yml
      with: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}